services:
  - type: web
    name: osct
    runtime: node
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
